---
title: "9/25/19 In class activities"
author: "One4All"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(nycflights13)

flights

```

```{r}
flights %>% filter(is.na(arr_time)) %>% group_by(year, month, day) %>% summarize(count=n()) %>% arrange(desc(count)) 
```


```{r}
flights %>% filter(dest == "DEN") %>% group_by(carrier) %>% summarize(count = n()) %>% arrange(desc(count))
```

```{r}
flights %>% filter(dest == "DEN") %>% mutate(delay=abs(sched_arr_time - arr_time)) %>% group_by(carrier) %>%  summarize(column = 100 * mean(delay < 15, na.rm = TRUE))  %>% arrange(desc(column))
```




```{r}
flights%>%filter(carrier=='UA'&!is.na(arr_time))%>%group_by(carrier)%>%summarise(total=n())
```


```{r}
total<-flights%>%filter(!is.na(arr_time))%>%summarize(total=n())
total=total[1,1]
total

```

```{r}
57916/328063
```

```{r}
num<-flights%>%filter(dest=='DEN'&month==9&day==30&!is.na(arr_time))%>%summarize(total=n())
num<-num[1,1]
num
```

```{r}
num/total
```

```{r}
den<-flights%>%filter(month==9&day==30&!is.na(arr_time)&dest=="DEN")
den

```

```{r}
den%>%filter(arr_delay>=15)%>%summarize(total=n())%>%print()


```

```{r}
long_flights=flights%>%filter(air_time>=5*60&!is.na(arr_time))
long_flights
```

```{r}
late_long<-long_flights%>%filter(arr_delay>15)
length(late_long$arr_time)/length(long_flights$arr_time)
```

```{r}
short<-flights%>%filter(!is.na(arr_time)&air_time<2*60)

late_short<-short%>%filter(arr_delay>15)
length(late_short$arr_time)/length(short$arr_time)
```

```{r}
DEN<-flights%>%filter(dest=='DEN'&!is.na(arr_time))
DEN_early<-DEN%>%filter(arr_delay<0)
length(DEN_early$arr_time)/length(DEN$arr_time)
```

```{r}
united<-flights%>%filter(carrier=="UA"&!is.na(arr_time))
u_late_bitch<-united%>%filter(arr_delay>60)
length(u_late_bitch$arr_time)/length(united$arr_time)
```

```{r}
uden<-flights%>%filter(dest=="DEN"&carrier=="UA"&!is.na(arr_time))
uden_early<-uden%>%filter(arr_delay<0)
length(uden_early$arr_time)/length(uden$arr_time)
```

```{r}
uden<-flights%>%filter(dest=="DEN"&carrier=="UA"&!is.na(arr_time))
uden_late<-uden%>%filter(arr_delay>15)
length(uden_late$arr_time)/length(uden$arr_time)
```

```{r}
late_flights<-flights%>%filter(!is.na(arr_time)&arr_delay>15)
jfk_late<-late_flights%>%filter(origin="JFK")
lga_late<-late_flights%>%filter(origin="LGA")
ewr_late<-late_flights%>%filter(origin="EWR")
length(jfk_late$arr_time)/length(late_flights$arr_time)
```


