---
title: "LA15 one4all"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
```

```{r}
df <- read_csv(file = "data1.csv", col_types=cols(CreationDate=col_datetime()))
info <- read_csv(file = "data2.csv")

colnames(df) <- c("Country", "Abbreviation", "Measuring", "Code", "1995", "1996", "1997", "1998", "1999", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")


worlddata <- df %>% group_by(Country) %>% nest()
df<-df[,-29]


df<-df%>%gather(`1995`:`2019`,key=year,value=measurement)%>%select(Country,Measuring,year,measurement)%>%filter(Country!="Data from database: World Development Indicators")%>%
  filter(Country!="Last Updated: 10/28/2019")%>%filter(!is.na(Country))




countries<-unique(df$Country)
#countries

afghanistan<-df%>%filter(Country=="Afghanistan")%>%spread(key=Measuring,value=measurement)



cleaned<-afghanistan

countries<-countries[-1]
for(i in 1:length(countries)){
  temp<-df%>%filter(Country==countries[i])%>%spread(key=Measuring,value=measurement)
  cleaned<-rbind(cleaned,temp)
}



cleaned


```

```{r}
colnames(cleaned)
```

```{r}
tdata<-cleaned%>%select(Country,year,GDPpc=`GDP per capita (current US$)`,Literacy= `Literacy rate, adult total (% of people ages 15 and above)`,Life_exp=`Life expectancy at birth, total (years)`,
                        HIV=`Women's share of population ages 15+ living with HIV (%)`)

tdata<-tdata%>%mutate(year=as.double(year),GDPpc=as.double(GDPpc),Literacy=as.double(Literacy),Life_exp=as.double(Life_exp),HIV=as.double(HIV))

tdata


```







